name = "disnake-era-template"
description = "Internal kickstart template for new disnake-era projects."
kickstart_version = 1
url = "https://github.com/disnake-era/template"
authors = ["elenakrittik <dev.elenakrittik@gmail.com>"]
keywords = ["disnake", "disnake.ext", "discord", "disnake-era"]

ignore = ["README.md"]
directory = "disnake-ext-{{ project_name }}"
copy_without_render = ["*.jinja", ".github/workflows/"]

[[variables]]
name = "project_name"
default = "plugins"
prompt = "Name your creation (part that comes after disnake-ext-)?"

[[variables]]
name = "project_description"
default = ""
prompt = "What all of this is about (description)?"

[[variables]]
name = "author_name"
default = "elenakrittik"
prompt = "Your name (your PyPI/GitHub username, usually)?"

[[variables]]
name = "author_email"
default = "dev.elenakrittik@gmail.com"
prompt = "Your contact email?"

[[variables]]
name = "spdx_license"
default = "MIT"
prompt = "Which license do you want to pick (SPDX identifier)?"
